import { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Button } from '@/components/ui/Button'; import { Spinner } from '@/components/ui/Spinner'; import { ErrorState } from '@/components/ui/ErrorState'; import { EmptyState } from '@/components/ui/EmptyState'; import { couponsApi } from '@/services/apiClient';

export function AdminCouponsPage() {
  const { i18n } = useTranslation(); const isArabic = i18n.language === 'ar'; const [rows, setRows] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [formError, setFormError] = useState<string | null>(null); const [saving, setSaving] = useState(false); const [form, setForm] = useState({ code: '', discountType: 'percentage', discountValue: '10', minimumOrderAmount: '', usageLimit: '', isActive: true });
  const load = async () => { setLoading(true); try { const res = await couponsApi.adminList({ limit: 100 }); setRows((res.data as any[]) || []); setError(null); } catch (e) { setError(e instanceof Error ? e.message : (isArabic ? 'حدث خطأ' : 'Failed')); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const submit = async (e: React.FormEvent) => { e.preventDefault(); setSaving(true); setFormError(null); try { await couponsApi.create({ code: form.code.trim().toUpperCase(), discountType: form.discountType, discountValue: Number(form.discountValue), minimumOrderAmount: form.minimumOrderAmount ? Number(form.minimumOrderAmount) : undefined, usageLimit: form.usageLimit ? Number(form.usageLimit) : undefined, isActive: form.isActive }); setForm({ code: '', discountType: 'percentage', discountValue: '10', minimumOrderAmount: '', usageLimit: '', isActive: true }); await load(); } catch (err) { setFormError(err instanceof Error ? err.message : (isArabic ? 'فشل الحفظ' : 'Failed')); } finally { setSaving(false); } };
  const onDelete = async (id: string) => { if (!confirm(isArabic ? 'هل تريد حذف الكوبون؟' : 'Delete coupon?')) return; setFormError(null); try { await couponsApi.remove(id); await load(); } catch (err) { setFormError(err instanceof Error ? err.message : (isArabic ? 'فشل الحذف' : 'Delete failed')); } };
  const toggleActive = async (c: any) => { setFormError(null); try { await couponsApi.update(c._id, { isActive: !c.isActive }); await load(); } catch (err) { setFormError(err instanceof Error ? err.message : (isArabic ? 'فشل التحديث' : 'Update failed')); } };
  return <div><h2 className="font-display text-2xl font-semibold">{isArabic ? 'كوبونات الخصم' : 'Coupons'}</h2><form onSubmit={submit} className="mt-6 grid gap-3 rounded-xl border border-border p-4 sm:grid-cols-2 lg:grid-cols-3"><input className="rounded-lg border border-border bg-background px-3 py-2 text-sm" placeholder={isArabic ? 'رمز الكوبون' : 'CODE'} value={form.code} onChange={e => setForm({ ...form, code: e.target.value })} required /><select className="rounded-lg border border-border bg-background px-3 py-2 text-sm" value={form.discountType} onChange={e => setForm({ ...form, discountType: e.target.value })}><option value="percentage">{isArabic ? 'نسبة مئوية' : 'percentage'}</option><option value="fixed">{isArabic ? 'قيمة ثابتة' : 'fixed'}</option></select><input className="rounded-lg border border-border bg-background px-3 py-2 text-sm" placeholder={isArabic ? 'قيمة الخصم' : 'Value'} type="number" value={form.discountValue} onChange={e => setForm({ ...form, discountValue: e.target.value })} required /><input className="rounded-lg border border-border bg-background px-3 py-2 text-sm" placeholder={isArabic ? 'الحد الأدنى للطلب' : 'Min order'} type="number" value={form.minimumOrderAmount} onChange={e => setForm({ ...form, minimumOrderAmount: e.target.value })} /><input className="rounded-lg border border-border bg-background px-3 py-2 text-sm" placeholder={isArabic ? 'حد الاستخدام' : 'Usage limit'} type="number" value={form.usageLimit} onChange={e => setForm({ ...form, usageLimit: e.target.value })} /><Button type="submit" disabled={saving}>{isArabic ? 'إضافة' : 'Create'}</Button></form>
    {formError && <p className="mt-3 text-sm text-error" role="alert">{formError}</p>}{loading ? <div className="flex justify-center py-12" role="status"><Spinner /></div> : error ? <ErrorState className="mt-4" message={error} onRetry={() => void load()} /> : rows.length === 0 ? <EmptyState className="mt-8" title={isArabic ? 'لا توجد كوبونات' : 'No coupons'} description={isArabic ? 'أضف أكواد الخصم هنا.' : 'Create WELCOME15 or seasonal codes here.'} /> : <div className="mt-6 overflow-x-auto rounded-xl border border-border"><table className="w-full min-w-[560px] text-sm"><thead className="border-b bg-surface text-muted-foreground"><tr><th className="px-4 py-3 text-start">{isArabic ? 'الكود' : 'Code'}</th><th className="px-4 py-3 text-start">{isArabic ? 'النوع' : 'Type'}</th><th className="px-4 py-3 text-start">{isArabic ? 'القيمة' : 'Value'}</th><th className="px-4 py-3 text-start">{isArabic ? 'المستخدم' : 'Used'}</th><th className="px-4 py-3 text-start">{isArabic ? 'نشط' : 'Active'}</th><th /></tr></thead><tbody>{rows.map(c => <tr key={c._id} className="border-b last:border-0"><td className="px-4 py-3 font-mono font-medium">{c.code}</td><td className="px-4 py-3">{c.discountType === 'percentage' ? (isArabic ? 'نسبة مئوية' : 'percentage') : (isArabic ? 'قيمة ثابتة' : 'fixed')}</td><td className="px-4 py-3">{c.discountValue}</td><td className="px-4 py-3">{c.usedCount ?? 0}{c.usageLimit != null ? ` / ${c.usageLimit}` : ''}</td><td className="px-4 py-3">{c.isActive ? (isArabic ? 'نعم' : 'Yes') : (isArabic ? 'لا' : 'No')}</td><td className="px-4 py-3 text-end space-x-2"><Button size="sm" variant="ghost" onClick={() => void toggleActive(c)}>{c.isActive ? (isArabic ? 'تعطيل' : 'Disable') : (isArabic ? 'تفعيل' : 'Enable')}</Button><Button size="sm" variant="ghost" onClick={() => void onDelete(c._id)}>{isArabic ? 'حذف' : 'Delete'}</Button></td></tr>)}</tbody></table></div>}
  </div>;
}
